name: 'Dependabot JIRA Action'
description: 'Creates JIRA issues from dependabot alerts'
author: 'Khairajani Author'
inputs:
  jiraIssueLabel:
    required: true
    description: 'JIRA issue labels'
    default: "dependabot"
  jiraProjectKey:
    required: true
    description: 'JIRA issue project key'
  jiraIssueType:
    required: true
    description: 'JIRA issue type'
    default: "Bug"
  githubRepo:
    required: true
    description: 'Repo to look for dependabot pulls'
    default: "code_scan"
  githubOwner:
    required: true
    description: 'Owner of the repo'
    default: "Khairajani"
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'copy'
  color: 'purple'
